name: Sync Main to Feature Branches

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Merge to Feature Branches
        run: |
          for branch in kavindu; do
            git checkout $branch
            git merge master || true
            git push origin $branch
          done
