name: Sync Main to Feature Branches

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Merge to Feature Branches
        run: |
          git fetch origin
          git checkout master
          git pull origin master
          
          for branch in member/kavindu member/dilnaka member/geenuth member/rayon member/venul member/savina2; do
            echo "Processing $branch"
            git checkout $branch
            git pull origin $branch
            git merge master || (echo "Conflict in $branch" && git merge --abort && continue)
            git commit -am "Sync with master" || echo "No changes to commit in $branch"
            git push origin $branch
            git reset --hard
            git clean -fd
          done
